export const cuisineList = [
    "Breakfast",
    "Burgers",
    "Pizza",
    "Fast Food",
    "Italian",
    "Mexican",
    "Chinese",
    "Indian",
    "Thai",
    "Japanese",
    "Vietnamese",
    "French",
    "Healthy",
    "Dessert",
    "Drinks",
    "Sushi",
    "Seafood",
    "Vegetarian",
]